/**
 * Lumen stylesheet build.
 *
 * Plain CSS concatenation with `@import` inlining — no Tailwind, and no CSS
 * toolchain at all.
 *
 * Tailwind was here and was not being used as Tailwind. The markup is
 * semantic (`btn btn-primary`, `chip chip-quiet`) and the styling lives in
 * hand-written component sheets; the utility engine emitted 87 selectors of
 * which exactly one (`sr-only`) appeared in any markup, the other 86 being
 * false positives its source scanner extracted from ordinary JavaScript —
 * `display:block`, `el.hidden`, `flex`, `grid`, `table`, `truncate`. That was
 * ~9KB of dead CSS per surface, growing with the JS rather than with the
 * design. What Tailwind actually provided was `@import` bundling, which is
 * the twenty lines below.
 *
 * Two entries, not one. The two outputs used to be byte-identical, so the web
 * app shipped the side panel's component CSS and the side panel shipped the
 * web app's — plus the Frank coach's, which is injected into a shadow root by
 * scripts/build-extension.mjs and belongs in neither document sheet.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const UI = path.join(root, 'packages/ui');

/** Each surface gets its own sheet: the shared palette, then only its own
 * components. `packages/ui/tokens.css` is the single source of the palette —
 * nothing downstream may redeclare a colour it already names. */
export const CSS_ENTRIES = {
  panel: ['packages/ui/tokens.css', 'apps/extension/sidepanel.css'],
  web: ['packages/ui/tokens.css', 'packages/ui/web.css']
};

/** Inlines `@import "./x.css"` recursively so a sheet can be authored in
 * pieces and still ship as one file. */
function inlineImports(file, seen = new Set()) {
  const abs = path.resolve(root, file);
  if (seen.has(abs)) return '';
  seen.add(abs);
  const dir = path.dirname(abs);
  return fs.readFileSync(abs, 'utf8').replace(
    /^@import\s+["']([^"']+)["']\s*;\s*$/gm,
    (_line, ref) => inlineImports(path.relative(root, path.resolve(dir, ref)), seen)
  );
}

export function compileLumenCss(outFile, entry = 'panel') {
  const parts = CSS_ENTRIES[entry];
  if (!parts) throw new Error(`Unknown Lumen CSS entry "${entry}".`);
  const header = `/* Lumen ${entry} stylesheet — generated by scripts/build-css.mjs. Edit ${parts.join(', ')}. */\n`;
  const css = parts.map((p) => inlineImports(p).trim()).filter(Boolean).join('\n\n');
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, `${header}${css}\n`);
  return outFile;
}

/** The token block as it should appear inside a shadow root's `:host`.
 *
 * The Site Audit overlay and the Frank coach inject their CSS into shadow
 * roots on third-party pages under `:host{all:initial}`, so they can never
 * load a compiled sheet — which is exactly why they grew private copies of
 * the palette that then drifted from it. This hands them the real thing at
 * build time, the same way the coach's stylesheet is already injected.
 */
export function lumenTokenBlock() {
  const css = fs.readFileSync(path.join(UI, 'tokens.css'), 'utf8');
  const match = css.match(/:root\s*\{([\s\S]*?)\n\}/);
  if (!match) throw new Error('packages/ui/tokens.css no longer exposes a :root block to inject.');
  return match[1].trim();
}

export function buildLumenCss({ extensionCss, webCss } = {}) {
  const written = [];
  if (extensionCss) written.push(compileLumenCss(extensionCss, 'panel'));
  if (webCss) written.push(compileLumenCss(webCss, 'web'));
  return written;
}

if (import.meta.url === `file:///${process.argv[1].replace(/\\/g, '/')}`) {
  const written = buildLumenCss({
    extensionCss: path.join(root, 'dist/extension/sidepanel.css'),
    webCss: path.join(root, 'apps/web/public/styles.css')
  });
  for (const file of written) {
    console.log(`${path.relative(root, file)} — ${(fs.statSync(file).size / 1024).toFixed(1)}KB`);
  }
}
